FROM golang:1.16-stretch
LABEL maintainer="github@github.com"

# Update stretch repositories
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/stretch-updates/d' /etc/apt/sources.list

RUN useradd -m testuser

RUN apt-get update
RUN apt-get install -y lsb-release
RUN rm -rf /var/lib/apt/lists/*

COPY . /go/src/github.com/github/freno
WORKDIR /go/src/github.com/github/freno

RUN chown -R testuser .
USER testuser

CMD ["script/test"]
