#!/bin/sh

set -e

script/build

# Get a fresh directory and make sure to delete it afterwards
build_dir=tmp/build
rm -rf $build_dir
mkdir -p $build_dir
trap "rm -rf $build_dir" EXIT

commit_sha=$(git rev-parse HEAD)

if [ $(uname -s) = "Darwin" ]; then
    build_arch="$(uname -sr | tr -d ' ' | tr '[:upper:]' '[:lower:]')-$(uname -m)"
else
    build_arch="$(lsb_release -sc | tr -d ' ' | tr '[:upper:]' '[:lower:]')-$(uname -m)"
fi

tarball=$build_dir/${commit_sha}-${build_arch}.tar

# Create the tarball
tar cvf $tarball bin/

# Compress it and copy it to the directory for the CI to upload it
gzip $tarball
mkdir -p "$BUILD_ARTIFACT_DIR"/freno
cp ${tarball}.gz "$BUILD_ARTIFACT_DIR"/freno/

### HACK HACK HACK ###
# blame @carlosmn, @mattr, @timvaillancourt and @rashiq
# Allow builds on buster to also be used for focal
focal_tarball_name=$(echo $(basename "${tarball}") | sed s/-stretch-/-focal-/)
cp ${tarball}.gz "$BUILD_ARTIFACT_DIR/freno/${focal_tarball_name}.gz"
