#!/bin/bash

set -e

. script/bootstrap

mkdir -p bin

version=$(git rev-parse HEAD)
describe=$(git describe --tags --always --dirty)

# We put the binaries directly into the bindir, because we have no need for shim wrappers
go build -o "bin/freno" -ldflags "-X main.AppVersion=${version} -X main.BuildDescribe=${describe}" ./cmd/freno/main.go
